name: Run tests
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create .env file
        run: cp development.env .env

      - name: Build docker image
        run: docker compose build
        
      - name: Run tests in docker container
        run: docker compose run tests-dummy test
